### ISSUE TITLE
Problems with installing addon

### ISSUE THREAD

**Issue by helloDanuk** [statamic-rad-pack/campaign-monitor#8]
### Description

On a fresh statamic 5.7.2 install I get error messages when trying to install the campaign monitor addon.

first attempt `$ composer require statamic-rad-pack/campaign-monitor` gets this error message:

<img width="672" alt="Bildschirmfoto 2024-06-12 um 21 45 23" src="https://github.com/statamic-rad-pack/campaign-monitor/assets/8265902/c7ff2b1e-c5e2-4c9f-a33b-e3809587389d">

second attempt `$ composer require statamic-rad-pack/campaign-monitor` get this error message:

<img width="692" alt="Bildschirmfoto 2024-06-12 um 21 47 34" src="https://github.com/statamic-rad-pack/campaign-monitor/assets/8265902/8c763f8d-7c89-426e-a5ed-3a04b95e681a">

### Steps to reproduce

```
$ statamic new test
$ composer require statamic-rad-pack/campaign-monitor
```

### Environment

Environment
Application Name: Statamic
Laravel Version: 11.10.0
PHP Version: 8.3.7
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: cm.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.2 Solo

Statamic Addons
edalzell/forma: 3.0.1
statamic-rad-pack/campaign-monitor: 2.0.0

**Comment by ryanmitchell** [comment]
Ah the release action failed - thanks for letting me know.

I've pushed out 2.0.1 which should fix this!

**Comment by helloDanuk** [comment]
Thank you for looking into this so quickly. Unfortunately, I still get the same error when I try to install it in a new Statamic installation.

**Comment by ryanmitchell** [comment]
I was being silly - 2.0.2 should ACTUALLY fix it!

**Comment by helloDanuk** [comment]
Thanks!
